### ISSUE TITLE
"HTTPError: Response code 400 (Bad Request)"

### ISSUE THREAD

**Issue by RobMeerwijk** [ksacca/daikincloud-domoticz#1]
Hi, I have used your node-red/mqtt solution a few months. Since Feb 12th I have lost the connection with Daikin Cloud. I get a 400 Bad Request answer from the cloud. I am not aware of relevant changes that might have caused this behaviour. Has the cloud api been changed? 

Changing the setting to debug does not provide extra information. I have checked out js-source code and I found the url https://cdc.daikin.eu/accounts.login When I tried this link I got a 400 Bad reqest and the message told me that the version 2 API key was invalid.Does this tell you something. Did they withdraw the api-key?

> {
  "callId": "cf6f3c056f1b443a9f41ed42ac4eea8d",
  "errorCode": 400093,
  "errorDetails": "Missing required parameter: ApiKey",
  "errorMessage": "Invalid ApiKey parameter",
  "apiVersion": 2,
  "statusCode": 400,
  "statusReason": "Bad Request",
  "time": "2023-02-22T01:09:02.375Z"
}

Thanks for your answer!

**Comment by RobMeerwijk** [comment]
Possibly caused by https://github.com/Apollon77/daikin-controller-cloud/issues/97 ?

**Comment by skycrack-77** [comment]
Okay, since today i have the same Issue,
"HTTPError: Response code 400 (Bad Request)" without any changes in configuration. Is there any Workarround to get an fuctionality state ? Best Regards Rene

**Comment by ksacca** [comment]
Sorry. I've been away for a while and did not really work further on this solution.
Do you guys still have this issue? On my side the "save token" option is disabled and I don't really have any issues connecting.

**Comment by RobMeerwijk** [comment]
No problem! And yes I do. I get a 400 error. My workaround is to use the app in stead of domoticz to control the Daikin. When I tried to get a token manually I ran into a new error, see above. But this may actually be the root cause of this problem. Is that right?

**Comment by RobMeerwijk** [comment]
I have tried both with and without saving token option. Doesn´t work. I don´t know where I could find debug info. Do you know? It just stopped working after 30 days and I don´t know where to look for a solution.

**Comment by RobMeerwijk** [comment]
Suddenly the fow is functional again. Nothing changed on my site. Thanks anyway for the great work!
